name: Instagram Bulk Creator

on:
  workflow_dispatch:
    inputs:
      ACCOUNT_COUNT:
        description: 'Number of accounts to create'
        required: true
        default: '1'
      PASSWORD_SUFFIX:
        description: 'Password suffix to append'
        required: true
        default: '123'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run account creator
      env:
        ACCOUNT_COUNT: ${{ github.event.inputs.ACCOUNT_COUNT }}
        PASSWORD_SUFFIX: ${{ github.event.inputs.PASSWORD_SUFFIX }}
      run: node index.js

    - name: Upload accounts CSV
      uses: actions/upload-artifact@v4
      with:
        name: insta-accounts
        path: accounts.csv
