name: Insta Bulk Creator

on:
  workflow_dispatch:

jobs:
  create_accounts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node index.js

    - name: Upload accounts.csv
      uses: actions/upload-artifact@v3
      with:
        name: insta-accounts
        path: accounts.csv
